name: mario_game
description: A Flutter game project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
